on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: Check Lint Test
jobs:
  lint:
    name: Check Lint Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: cargo check
        run: cargo check --all --all-features --benches --tests

      - name: cargo fmt
        run: cargo fmt --all --check

      - name: cargo clippy
        run: cargo clippy --all --all-features --benches --tests

      - name: cargo test
        run: cargo test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract short SHA
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV

      - name: Build (without push)
        uses: docker/build-push-action@v5
        if: github.event_name == 'pull_request'
        with:
          context: .
          push: false
          tags: |
            ultrasoundorg/payload-validator:${{ env.SHORT_SHA }}
            ultrasoundorg/payload-validator:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

